# Generated by Django 3.1.4 on 2023-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='icc_id',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='msisdn',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='sim',
            name='package',
        ),
        migrations.AddField(
            model_name='sim',
            name='ICC_ID',
            field=models.CharField(default=2323, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sim',
            name='MSISDN',
            field=models.CharField(default='013132', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sim',
            name='OPERATOR',
            field=models.CharField(choices=[('zong', 'Zong'), ('ufone', 'Ufone'), ('warid', 'Warid'), ('mobilink', 'Mobilink'), ('telenor', 'Telenor')], default='Zong', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sim',
            name='PACKAGE',
            field=models.CharField(default='1000', max_length=50),
            preserve_default=False,
        ),
    ]
